setup-and-mobile-version-skeleton
brainskev/setup-and-mobile-version-skeleton pull request #7
Opened 2022-10-28 13:50 UTC by brainskev

Used design template
imported recommended fonts
Added header
Added recommended text styling

2022-10-28 16:08 UTC, cynthiainga requested changes
Hi @brainskev, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

 ## Required Changes ♻️

- [ ] Please as required by the previous reviewers, you should make sure that your design stick as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
  - Kindly fix the white space to the right side of your website, you need to remove the width of your `section.Headline` class in your `CSS` file 🙃 🙃
  - Kindly make sure the space between your elements is the same as in the Figma design 😁 
  - The background image has a border-radius to the left, please kindly fix that as well 😁 😁

Your design

<img width="287" alt="Screen Shot 2022-10-28 at 17 26 49" src="https://user-images.githubusercontent.com/74501523/198681225-cdbbd78e-d286-4dcc-8d5a-9022a173ae0d.png">

Figma design

<img width="321" alt="Screen Shot 2022-10-28 at 17 27 18" src="https://user-images.githubusercontent.com/74501523/198681356-a5dbfe47-c257-40fb-a6ed-df98e7bce399.png">


- [ ] As required by the previous reviewers the hamburger should be inside the nav tag. The nav tag is for semantics reasons, please kindly put it inside the `nav` tag 😁 😁 

<img width="272" alt="Screen Shot 2022-10-28 at 17 31 28" src="https://user-images.githubusercontent.com/74501523/198681425-7747ff66-6725-4174-b2f1-533848dd95b8.png">

- [ ] Please don't open a new Pull Request when you will ask for the next review. It's better to submit the same Pull Request, which allows code reviewers to proceed to the review without any confusion, and also code reviewers can see directly what changes the previous reviewer requested from you 🙃 🙃 

## Optional suggestions

- [OPTIONAL] I suggest you add the Getting started information in your README file, explain to users how they can get your project locally, how they can open it locally, things that they need in their device,... 🙃 😉
- [OPTIONAL] The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Please remember this in your next commits 😁 😉 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 10:43 UTC, PinkMoon25 approved these changes
Hi @brainskev , :wave:  

Great job implementing all the changes :clap: 
Your projct is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/26DOoDwdNGKAg6UKI/giphy-downsized-medium.gif"/>

## Highlights
 No linters errors :heavy_check_mark: 
 Descriptive PR :heavy_check_mark: 
 Correct Github flow  :heavy_check_mark: 
 Used flexbox for layout  :heavy_check_mark: 

## Optional suggestions
_**I have added some optional changes in order to improve our site, please see them below**_ :pray: 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 10:43 UTC, PinkMoon25 commented on index.html
>                  </div>
[OPTIONAL] ad requested by the previous reviewer this section shoul be like this :point_down: , as this is semantically more appropriate
```
<nav class="humberger">
            <div class="bar"></nav>
            <div class="bar"></nav>
             <div class="bar"></nav>
</nav>
```

2022-10-29 10:43 UTC, PinkMoon25 commented on index.html
> +                    <p id="two">LET'S CONNECT</p>
[OPTIONAL] As this is a call to action putting it inside a link <a> or button tag would be more appropriate, what do you think? :thinking:

2022-10-29 10:43 UTC, PinkMoon25 commented on index.html
>                      </svg></a>
Each element inside a `<ul>` tag id generally `<li>` tag, you have placed the social icons in a` <a>` tag which is correct :+1: , but i would suggest please add each of these `<a>` tags inside a `<li>` tag

2022-10-29 16:46 UTC, merged